SSKB/KnowledgeBase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('kb/', include('kb.urls')),    # Use this path for keeping the app in a subfolder
    path('', include('kb.urls')),       # No subfolder, root is app
]

SSKB/kb/urls.py
from django.urls import path
from . import views

app_name = 'kb'

urlpatterns = [
    path('', views.index, name='index'),

    # User login/logout
    path('login', views.login, name='login'),
    path('login/submit', views.login_do, name='login_do'),
    path('logout', views.logout, name='logout'),

    # Folder paths
    path('folder/<int:folder_id>/', views.folder, name='folder'),
    path('folder/<int:folder_id>/newfolder', views.folder_new, name='folder_new'),
    path('folder/<int:folder_id>/addfolder', views.folder_add, name='folder_add'),
    path('folder/<int:folder_id>/permissions', views.folder_perms, name='folder_perms'),

    # Article creation
    path('folder/<int:folder_id>/newarticle', views.article_new, name='article_new'),
    path('folder/<int:folder_id>/newarticle/action', views.article_new_action, name='article_new_action'),

    # Article view/edit
    path('article/<int:article_id>/', views.article, name='article'),
    path('article/<int:article_id>/edit', views.article_edit, name='article_edit'),
    path('article/<int:article_id>/edit/action', views.article_edit_action, name='article_edit_action'),
    path('article/<int:article_id>/history', views.article_history, name='article_history'),
    path('article/<int:article_id>/history/<int:version>', views.article_version, name='article_version'),
    path('article/<int:article_id>/history/<int:version>/activate', views.article_version_activate, name='article_version_activate'),

    # search
    path('search/', views.search, name="search"),
]

SSKB/kb/views.py
import datetime
import sqlite3
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.utils.html import strip_tags
from django.db.models.functions import Lower
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from .models import Folder, Article, History, FolderPerm

# Display login form
def login(request):
    return render(request, 'kb/login.html')


# Do login
def login_do(request):
    username = request.POST['username']
    passwd = request.POST['password']

    user = authenticate(request, username=username, password=passwd)
    if user is not None:
        django_login(request, user)
        return HttpResponseRedirect(reverse('kb:index'))
    else:
        context = {
            'errormsg': 'Unable to authenticate! Please check your username and password.'
        }
        return render(request, 'kb/login.html', context)

# Logout
@login_required(login_url='kb:login')
def logout(request):
    django_logout(request)
    return HttpResponseRedirect(reverse('kb:index'))


# Display default page
@login_required(login_url='kb:login')
def index(request):
    Folder.init()
    root = Folder.home_folder()
    top_folders = Folder.objects.filter(parent=root).order_by('name')
    context = {
        'title': 'Home',
        'this_folder': root,
        'user_can_write': root.user_can_write(request.user),
        'show_sidebar': True,
        'show_breadcrumbs': True,
    }
    return render(request, 'kb/index.html', context)


# View articles and/or subfolders within the selected folder
@login_required(login_url='kb:login')
def folder(request, folder_id):
    this_folder = get_object_or_404(Folder, pk=folder_id)

    # Check user permissions
    if this_folder.user_can_read(request.user):

        # Redirect to Index for root folder
        if (this_folder == Folder.home_folder()):
            return HttpResponseRedirect(reverse('kb:index'))

        # Not root folder, display articles and subfolders
        subfolders = Folder.objects.filter(parent=folder_id).order_by(Lower('name'))
        articles = Article.objects.filter(folder=this_folder)
        context = {
            'title': this_folder.name,
            'this_folder': this_folder,
            'articles': articles,
            'user_can_write': this_folder.user_can_write(request.user),
            'show_sidebar': True,
            'show_breadcrumbs': True,
        }
        return render(request, 'kb/folder.html', context)

    else:
        messages.error(request,'You do not have permission to view this folder!')
        return HttpResponseRedirect(reverse('kb:index'))


# Create a new folder within a folder or root
@login_required(login_url='kb:login')
def folder_new(request, folder_id):
    this_folder = Folder.objects.get(pk=folder_id)

    context = {
        'title': 'Add New Folder',
        'this_folder': this_folder,
        'show_breadcrumbs': True,
    }
    return render(request, 'kb/folder_new.html', context)


# Save the new folder object
@login_required(login_url='kb:login')
def folder_add(request, folder_id):
    # Double-check that parent folder exists
    folder_parent = get_object_or_404(Folder, pk=folder_id)

    # Sanitize name of new folder
    folder_name = strip_tags(request.POST['folder_name'])   # Remove any HTML
    folder_name = folder_name.strip()                       # Remove any whitespace at beginning/end

    # Check that a name was actually provided
    if folder_name == '':
        messages.error(request, "Folder name must be specified!")
        context = {
            'title': 'Add New Folder',
            'this_folder': folder_parent,
            'show_breadcrumbs': True,
        }
        return render(request, 'kb/folder_new.html', context)
    else:
        # Create new folder
        new_folder = Folder(name=folder_name, parent=folder_parent)
        new_folder.save()

        # Create default Permissions
        new_folder_perms = FolderPerm(folder=new_folder, group=None, mode='R')
        new_folder_perms.save()

        # Redirect browser to newly created folder
        return HttpResponseRedirect(reverse('kb:folder', args=(new_folder.id,)))
    endif


@login_required(login_url='kb:login')
def folder_perms(request, folder_id):
    this_folder = get_object_or_404(Folder, pk=folder_id)
    perm_groups = FolderPerm.objects.filter(folder=this_folder)

    if this_folder.user_can_write(request.user):
        context = {
            'title': 'Edit Permissions - ' + this_folder.name,
            'this_folder': this_folder,
            'perm_groups': perm_groups,
            'show_breadcrumbs': True,
            'show_sidebar': True,
        }
        return render(request, 'kb/folder_permissions.html', context)

    else:
        messages.error(request, "You do not have permissions to edit this folder!")
        return HttpResponseRedirect(reverse('kb:folder', args=(folder_id,)))

# View the active version of an article
@login_required(login_url='kb:login')
def article(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    active_version = article.active_version()
    user = request.user
    context = {
        'title': active_version.title,
        'this_folder': article.folder,
        'user_can_write': article.folder.user_can_write(user),
        'article': article,
        'active_version': active_version,
        'show_breadcrumbs': True,
    }
    return render(request, 'kb/article.html', context)


# 'article_version' uses the same page template as 'article' but overrides
# active_version with the specified version to view
@login_required(login_url='kb:login')
def article_version(request, article_id, version):
    article = get_object_or_404(Article, pk=article_id)
    specific_article_version = History.objects.get(article=article, version=version)
    context = {
        'title': specific_article_version.title,
        'this_folder': article.folder,
        'user_can_write': article.folder.user_can_write(request.user),
        'article': article,
        'active_version': specific_article_version,
        'show_breadcrumbs': True,
    }
    return render(request, 'kb/article.html', context)


# 'article_version_activate' sets a specific version of an article to the active one
# The previously active version will be deactivated
# Redirects to show the newly active version of the article
@login_required(login_url='kb:login')
def article_version_activate(request, article_id, version):
    article = get_object_or_404(Article, pk=article_id)
    specific_article_version = History.objects.get(article=article, version=version)

    article.deactivate_all_versions()
    specific_article_version.set_active()

    return HttpResponseRedirect(reverse('kb:article', args=(article.id,)))


# Create a new article in a folder
@login_required(login_url='kb:login')
def article_new(request, folder_id):
    # Double-check that parent folder exists
    this_folder = get_object_or_404(Folder, pk=folder_id)

    if this_folder.user_can_write(request.user):
        context = {
            'title': 'Create New Article',
            'this_folder': this_folder,
            'ckeditor': True,
            'show_breadcrumbs': True,
        }
        return render(request, 'kb/article_new.html', context)
    else:
        messages.error(request, 'You do not have permissions to edit this folder!')
        return HttpResponseRedirect(reverse('kb:folder', args=(folder_id,)))


# Save or preview a new article
@login_required(login_url='kb:login')
def article_new_action(request, folder_id):
    # Sanity check that parent folder exists
    this_folder = get_object_or_404(Folder, pk=folder_id)

    # Get action from the clicked button
    action = request.POST['action']

    # Cancel button clicked
    # Immediately return to folder listing
    if action == 'cancel':
        return HttpResponseRedirect(reverse('kb:folder', args=(this_folder.id,)))

    # Sanitize article title
    article_title = strip_tags(request.POST['article_title'])   # Remove any HTML
    article_title = article_title.strip()                       # Remove any whitespace at beginning/end

    # Now that we've cleaned up, check that a name was actually provided
    if article_title == '':
        action = 'abort'
        messages.error(request, "Title must be specified!")

    # Sanitize article content (TO DO)
    article_body = request.POST['article_body']

    # Preview article
    if action == 'preview':
        context = {
            'title': 'PREVIEW - ' + article_title,
            'this_folder': this_folder,
            'article_title': article_title,
            'article_body': article_body,
            'show_breadcrumbs': True,
        }
        return render(request, 'kb/article_new_preview.html', context)

    # Save article
    elif action == 'save':
        # Create new article object
        article = Article(folder=this_folder)
        article.save()

        # Create version 1 in history for this article
        article_history = History(article=article, version=1, pub_date=datetime.datetime.now(), title=article_title, content=article_body, author='System', is_active=True)
        article_history.save()

        return HttpResponseRedirect(reverse('kb:folder', args=(this_folder.id,)))

    # Abort
    elif action != 'abort':
        # Use already specified error message
        messages.warning(request, "Unknown action specified!")

    # Return to new article form
    # Messages defined above will be present
    context = {
        'title': 'Create New Article',
        'this_folder': this_folder,
        'ckeditor': True,
        'show_breadcrumbs': True,
    }
    return render(request, 'kb/article_new.html', context)

SSKB/kb/templates/kb/article.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h3 class="card-header">{{ article }}</h3>
  <div class="card-body">
    <div class="card-text">
      <!-- begin article content -->
      {{ active_version.content|safe }}
      <!-- end article content -->
    </div><!-- card-text -->
  </div><!-- card-body -->

  <div class="card-footer">
    <span class="float-right">
      <a href="{% url 'kb:article_history' article.id %}" class="btn btn-primary">History</a>
      {% if user_can_write %}
        {% if active_version.is_active %}<a href="{% url 'kb:article_edit' article.id %}" class="btn btn-primary">Edit</a>{% endif %}
        {% if not active_version.is_active %}<a href="{% url 'kb:article_version_activate' article.id active_version.version %}" class="btn btn-primary">Make Active</a>{% endif %}
      {% endif %}
    </span><!-- float-right -->
    <div class="small">Published: {{ active_version.pub_date }} (Version {{ active_version.version }})</div>
    <div class="small">Author: {{ active_version.author }}</div>
  </div>
</div><!-- card -->

{% endblock %}

SSKB/kb/templates/kb/article_edit.html
{% extends 'kb/default_template.html' %}

{% block content %}

<form action="{% url 'kb:article_edit_action' article.id %}" method="post">
  {% csrf_token %}

  <div class="card">
    <h5 class="card-header">Edit Article</h5>
    <div class="card-body">
      <div class="card-text">
          <div class="form-group">
            <label for="article_title">Title:</label>
            <input type="text" name="article_title" class="form-control" value="{{ active_article.title }}"/>
          </div>

          <div class="form-group">
            <label for="article_body">Article content:</label>
            <textarea name="article_body" id="article_body">
              {{ active_article.content }}
            </textarea>

            <!-- initialize ckeditor AFTER textarea -->
            <script>
              CKEDITOR.replace( 'article_body' );
            </script>
            <!-- END initialize ckedit -->

          </div> <!-- form-group -->
        </div> <!-- card-text -->
      </div> <!-- card-body -->
      <div class="card-footer">
        <div class="form-group">
          <div class="float-left">
            <a href="javascript:history.back()" class="btn btn-danger">Cancel</a>
          </div>
          <div class="float-right">
            <button class="btn btn-light" name="action" value="preview">Preview</button>
            <button class="btn btn-primary" name="action" value="save">Save</button>
          </div> <!-- float-right -->
        </div> <!-- form-group -->
    </div> <!-- card-footer -->
  </div><!-- card -->

  &nbsp;

</form>

{% endblock %}

SSKB/kb/templates/kb/article_edit_preview.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h5 class="card-header">Preview Article</h5>
  <div class="card-body">
    <div class="card-text">
      <h3 class="card-title">{{ article_title }}</h3>
      {{ article_body|safe }}
    </div> <!-- card-text -->
  </div><!-- card-body -->
  <div class="card-footer">
    <div class="float-left">
      <a href="javascript:history.back()" class="btn btn-light">&lt; Back</a>
    </div><!-- float-left -->
    <div class="float-right">
      <button class="btn btn-primary">Save</button>
    </div><!-- float-right -->
  </div><!-- card-footer -->
</div><!-- card -->

{% endblock %}

SSKB/kb/templates/kb/article_history.html
{% extends 'kb/default_template.html' %}

{% block content %}

<h3>Article History</h3>
<div class="list-group">
{% for h in article_history %}
  {% if h.is_active %}
  <a href="{% url 'kb:article_version' article.id h.version %}" class="list-group-item flex-column active">
  {% else %}
  <a href="{% url 'kb:article_version' article.id h.version %}" class="list-group-item flex-column">
  {% endif %}

    <h5>Version {{ h.version }} - {{ h.title }}</h5>
    <small>Published: {{ h.pub_date }}<br/>Author: {{ h.author }}</small>

  </a>
{% endfor %}
</div>

  &nbsp;

{% endblock %}

SSKB/kb/templates/kb/article_new.html
{% extends 'kb/default_template.html' %}

{% block content %}

<form action="{% url 'kb:article_new_action' this_folder.id %}" method="post">
  {% csrf_token %}

  <div class="card">
    <h5 class="card-header">New Article</h5>
    <div class="card-body">
      <div class="card-text">
          <div class="form-group">
            <label for="article_title">Title:</label>
            <input type="text" name="article_title" class="form-control"/>
          </div>

          <div class="form-group">
            <label for="article_body">Article content:</label>
            <textarea name="article_body" id="article_body"></textarea>

            <!-- initialize ckeditor AFTER textarea -->
            <script>
              CKEDITOR.replace( 'article_body' );
            </script>
            <!-- END initialize ckedit -->

          </div> <!-- form-group -->
        </div> <!-- card-text -->
      </div> <!-- card-body -->
      <div class="card-footer">
        <div class="form-group">
          <div class="float-left">
            <button class="btn btn-danger" name="action" value="cancel">Cancel</button>
          </div>
          <div class="float-right">
            <button class="btn btn-light" name="action" value="preview">Preview</button>
            <button class="btn btn-primary" name="action" value="save">Save</button>
          </div> <!-- float-right -->
        </div> <!-- form-group -->
    </div> <!-- card-footer -->
  </div><!-- card -->

  &nbsp;

</form>

{% endblock %}

SSKB/kb/templates/kb/article_new_preview.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h5 class="card-header">Preview Article</h5>
  <div class="card-body">
    <div class="card-text">
      <h3 class="card-title">{{ article_title }}</h3>
      {{ article_body|safe }}
    </div> <!-- card-text -->
  </div><!-- card-body -->
  <div class="card-footer">
    <div class="float-left">
      <a href="javascript:history.back()" class="btn btn-light">&lt; Back</a>
    </div><!-- float-left -->
    <div class="float-right">
      <button class="btn btn-primary">Save</button>
    </div><!-- float-right -->
  </div><!-- card-footer -->
</div><!-- card -->

{% endblock %}

SSKB/kb/templates/kb/default_template.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
  <meta charset="utf-8">
  {% if title %}
  <title>Knowledge Base - {{ title }}</title>
  {% else %}
  <title>Knowledge Base</title>
  {% endif %}

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'popper/popper.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>


  {% if ckeditor %}
  <script src="{% static 'ckeditor4/ckeditor.js' %}"></script>

  {% endif %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'kb:index' %}">Knowledge Base</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <!-- this is where navbar links would go... IF I HAD ONE!!! -->
      </ul>
      <form class="form-inline" method="post" action="{% url 'kb:search' %}">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" name="search_terms" placeholder="Search" aria-label="Search">
        <button class="btn btn-default mr-4 mr-sm-4" type="submit">Go</button>
      </form>
      <ul class="navbar-nav mr-sm-2">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menuUserDropdownLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expand="false">{{ request.user }}</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="menuUserDropdownLink">
            <a class="dropdown-item" href="{% url 'kb:logout' %}">Logout</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>

  &nbsp;

  <div class="container">

    {% if messages %}
      {% for m in messages %}
        {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">
        {% elif m.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
        <div class="alert alert-warning" role="alert">
        {% else %}
        <div class="alert alert-info" role="alert">
        {% endif %}
          {{ m }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}

    {% if errormsg %}
    <div class="alert alert-danger" role="alert">
      {{ errormsg }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

    {% if show_breadcrumbs %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {% for f in this_folder.path %}
        <li class="breadcrumb-item">
          <a href="{% url 'kb:folder' f.id %}">{{ f.name }}</a>
        </li>
        {% endfor %}
      </ol>
    </nav>
    {% endif %}

    <div class="row">

      {% if show_sidebar %}
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <nav class="nav flex-column nav-pills">
                {% if this_folder.child_folders %}
                  {% for f in this_folder.child_folders %}
                    <a href="{% url 'kb:folder' f.id %}" class="nav-link">{{ f.name }}</a>
                  {% endfor %}
                {% endif %}
              </nav>
            </div> <!-- end card-body -->
          </div><!-- end card -->
        </div><!-- end col-3 -->
        <div class="col-sm-9">
      {% else %}
        <div class="col-sm-12">
      {% endif %}

      <!-- BEGIN BLOCK CONTENT -->

      {% block content %}

      {% endblock %}

      <!-- END BLOCK CONTENT -->

    </div><!-- end col-sm-9/12 -->
    </div><!-- end row -->
  </div><!-- end container -->

</body>

</html>

SSKB/kb/templates/kb/folder.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h3 class="card-header">Articles</h3>
  <div class="card-body">
    <nav class="nav-flex-column">
      {% for a in articles %}
      <a href="{% url 'kb:article' a.id %}" class="nav-link">{{ a }}</a>
      {% endfor %}
    </nav>
  </div>
  {% if user_can_write %}
  <div class="card-footer">
    <a href="{% url 'kb:article_new' this_folder.id %}" class="btn btn-primary"><i class="far fa-file mr-sm-1"></i> Add Article</a>
    <a href="{% url 'kb:folder_new' this_folder.id %}" class="btn btn-primary"><i class="far fa-folder mr-sm-1"></i> Add folder</a>
    <a href="{% url 'kb:folder_perms' this_folder.id %}" class="btn btn-primary"><i class="fas fa-key mr-sm-1"></i> Edit Permissions</a>
  </div>
  {% endif %}
</div>

{% endblock %}

SSKB/kb/templates/kb/folder_new.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h5 class="card-header">Add subfolder to {{ this_folder.name }}</h5>
  <div class="card-body">
    <div class="card-text">

      <form action="{% url 'kb:folder_add' this_folder.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="folder_name">Name:</label>
          <input type="text" name="folder_name" class="form-control"/>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Add</button>
        </div>
      </form>

    </div><!-- card-text -->
  </div><!-- card-body -->
</div><!-- card -->

{% endblock %}

SSKB/kb/templates/kb/folder_permissions.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h5 class="card-header">{{ this_folder.name }} - Permissions</h5>
  <div class="card-body">
    <div class="card-text">

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Group</th>
            <th>Permissions</th>
            <th>Change</th>
          </tr>
        </thead>
        <tbody>
          {% for g in perm_groups %}
          <tr>
            <td>{{ g.group }}</td>
            <td>{{ g.mode }}</td>
            <td>
              <form class="form form-inline">
                {% csrf_token %}
                <select class="form-control mr-sm-2">
                  <option value="R">Read</option>
                  <option value="RW">Read/Write</option>
                  <option value="N">None</option>
                </select>
                <input type="submit" class="btn btn-primary" value="Save"/>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div><!-- card-text -->
  </div><!-- card-body -->
  <div class="card-footer">
    <a href="#" class="btn btn-primary">Add group</a>
  </div><!-- card-footer -->
</div><!-- card -->

{% endblock %}

SSKB/kb/templates/kb/index.html
{% extends 'kb/default_template.html' %}

{% block content %}

<div class="card">
  <h3 class="card-header">Statistics</h3>
  <div class="card-body">
    <div class="card-text">
      <div>
        Recently updated articles:
      </div>

      <div>
        New articles:
      </div>

      <div>
        Statistics:
      </div>
    </div>
  </div>
  <div class="card-footer">
    {% if user_can_write %}
      <a href="{% url 'kb:folder_new' this_folder.id %}" class="btn btn-primary"><i class="far fa-folder mr-sm-1"></i> Add folder</a>
      <a href="#" class="btn btn-primary"><i class="fas fa-key mr-sm-1"></i> Edit Permissions</a>
    {% endif %}
  </div>
</div>

{% endblock %}

SSKB/kb/templates/kb/login.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
  <meta charset="utf-8">
  <title>Knowledge Base - Login</title>

  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'popper/popper.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'kb:index' %}">Knowledge Base</a>
  </nav>

  &nbsp;

  <div class="container">

    {% if messages %}
      {% for m in messages %}
        {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">
        {% elif m.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
        <div class="alert alert-warning" role="alert">
        {% else %}
        <div class="alert alert-info" role="alert">
        {% endif %}
          {{ m }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}

    {% if errormsg %}
    <div class="alert alert-danger" role="alert">
      {{ errormsg }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

    <div class="row">
      <div class="col-sm-12">

        <div class="card">
          <h3 class="card-header">Please Login</h3>
          <div class="card-body">
            <form method="POST" action="{% url 'kb:login_do' %}">
              {% csrf_token %}
              <div class="form-group row">
                <label for="username" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                  <input class="form-control" type="text" name="username">
                </div>
              </div>
              <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                  <input class="form-control" type="password" name="password">
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-2">
                </div>
                <div class="col-sm-10">
                  <input type="submit" class="btn btn-primary" value="Login">
                </div>
              </div>
            </form>
          </div><!-- end card-body -->
        </div><!-- end card -->

      </div><!-- end col-sm-9/12 -->
    </div><!-- end row -->
  </div><!-- end container -->

</body>

</html>

SSKB/kb/templates/kb/search.html
{% extends 'kb/default_template.html' %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'kb:index' %}">Home</a>
    </li>
    <li class="breadcrumb-item">
      Results for '{{ terms }}'
    </li>
  </ol>
</nav>


<nav class="nav-flex-column">
  {% for a in results %}
  <a href="{% url 'kb:article' a.article_id %}" class="nav-link">{{ a.title }}</a>
  {% endfor %}
</nav>

{% endblock %}